---
- name: Fedora selinux state should be disabled for now
  selinux: state=disabled
  when: ansible_distribution == "Fedora"
- name: CentOS selinux state should be disabled (until fixed)
  selinux: state=disabled
  when: ansible_distribution == "CentOS"
